FROM python:3.11-alpine3.18

RUN     apk add --no-cache --virtual .build-deps gcc musl-dev make \
    &&  pip3 install --upgrade pip \
    &&  mkdir -p /opt/project

WORKDIR /opt/project

COPY requirements.in ./
RUN pip3 install -r requirements.in

CMD ["python3", "-m", "pyinstaller_project.main"]
