version: "3.9"

services:
  app-deb:
    image: debian:bookworm-slim
    volumes:
      - ./build/binaries:/bin-project
    entrypoint: /bin-project/pyinstaller_project_deb
    network_mode: host

  app-alpine:
    image: alpine:3.18
    volumes:
      - ./build/binaries:/bin-project
    entrypoint: /bin-project/pyinstaller_project_alpine
    network_mode: host
